# Generated by Django 3.0.5 on 2020-05-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200508_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent',
            new_name='sent_at',
        ),
    ]
