# Generated by Django 3.0.5 on 2020-05-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200505_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='static/img/rabbit-vector-26.jpg', upload_to='user/%Y/%m/%d/'),
        ),
    ]
