# Generated by Django 3.0.5 on 2020-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200505_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='rabbit-vector-26.jpg', upload_to='user/%Y/%m/%d/'),
        ),
    ]
