# Generated by Django 3.0.5 on 2020-05-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200512_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orientation',
            field=models.CharField(choices=[('bisexual', 'Bisexual'), ('heterosexual', 'Heterosexual'), ('homosexual', 'Homosexual')], default='male', max_length=12),
        ),
    ]
