# Generated by Django 3.0.5 on 2020-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='partner_age',
            field=models.CharField(choices=[('18-25', '18-25'), ('25-35', '25-35'), ('35-45', '35-45'), ('45-60', '45-60'), ('60+', '60+')], default='18-25', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='partner_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='partner_orientation',
            field=models.CharField(choices=[('bisexual', 'Bisexual'), ('heterosexual', 'Heterosexual'), ('homosexual', 'Homosexual')], default='heterosexual', max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='orientation',
            field=models.CharField(choices=[('bisexual', 'Bisexual'), ('heterosexual', 'Heterosexual'), ('homosexual', 'Homosexual')], default='heterosexual', max_length=12),
        ),
    ]
