# Generated by Django 3.0.5 on 2020-05-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='partner_age',
            field=models.CharField(choices=[('Young', '18-25'), ('Young_adult', '25-35'), ('Adult', '35-45'), ('Old_adult', '45-60'), ('Senior', '60+')], default='18-25', max_length=12),
        ),
    ]
