# Generated by Django 3.0.5 on 2020-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200528_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_base64',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
